### ISSUE TITLE
Using Pandas

### ISSUE THREAD

**Issue by jamayfieldjr** [python-metar/python-metar#87]
it this compatible with pandas. I need the visibility,wind speed, ceilings/clouds, time, Routine/Speci. Is there any easy way to output the data short and simple.

**Comment by akrherz** [comment]
Oh dear, I did not notice your issue here prior to you posting the same thing into MetPy.  Please don't spam projects like this, but use tools like [stackoverflow](https://stackoverflow.com) to ask questions like this.

Currently, we do not support Pandas, but this would be a nice addition to encapsulate all of the parsed data into a common data object.  To shamelessly promote my website, you can download processed METARs in csv [here](https://mesonet.agron.iastate.edu/request/download.phtml), but I don't think I have all the fields you want based on your MetPy issue.

**Comment by jamayfieldjr** [comment]
Sorry. I didn't know.

**Comment by phobson** [comment]
@jamayfieldjr my project Geosyntec/cloudside parses large files of METAR observations into dataframes
